Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  (1..2).each do |machine_id|
        config.vm.define "K8S#{machine_id}" do |cfg|
            cfg.vm.hostname = "k8s#{machine_id}"
            cfg.vm.provider :vmware_desktop do |v|
                v.vmx["memsize"] = "10240"
                v.vmx["numvcpus"] = "6"
            end
	        cfg.vm.network "private_network", ip: "192.168.88.#{machine_id+99}"
            cfg.vm.provision :shell, inline: <<-SHELL 
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCKisaFGCzMnXF5H3+xKXq9WQxEIo701qCUXnq7KSH+v60BK9XZN0zWbW4v9OTZ/4G7v13rCxVe6+A0VQIMZe33Q/dlFMuZt82/dy8LR/R8e2v3d8GlszhVl2Ti2YUN5C1uNaDF+dGDB3uEvKELQ4CLiypLrWwrrUuGu53ddh5u5nsB2tbeJaxKQLkHrKxLNDBnzO/Kt+M9vgF4fq9L2QfqBsgdF6ThmN7FMJVplIR/iXh+f+XBoaTUECm2sLaB9kd1mYX5BhtsQHa8wVQfnQ+NPeKyygkWTgHN2Sacdpcs7l4ddOSRpsbTdBmNVgzNORHkFlHRbA28nteYHVSxkL5 lab@f5" >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
    config.vm.provision 'ansible' do |ansible|
        ansible.playbook = 'playbook.yml'
        ansible.limit = "all"
        ansible.verbose = 'v'
        ansible.host_key_checking = false
    end
end